using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BangazonAPI.Models
{
    //SUMMARY
    /*This class is authored by Jordan Dhaenens. 
      PaymentType Class identifies the properties for the entries to the Customer Tabel in database*/
    public class PaymentType
    {
        /*This is the primary key for an entry on the PaymentType table. It is generated by the database and doesn't
        need to be submitted by the user*/
        [Key]
        public int PaymentTypeId { get; set; }
        //Property of PaymentType
        [Required]
        public Int64 AccountNumber { get; set; }
        //Property of PaymentType
        [Required]
        public string Type { get; set; }
        //Property of PaymentType
        [Required]
        public int CustomerId { get; set; }
        
        //This allows PaymentType to accept an instance of class Customer
        public Customer Customer { get; set; }

        //The following collections represent tables in which PaymentTypeId is a Foreign Key
        public ICollection<Order> Orders;
    }
}
